### ISSUE TITLE
XML for installation - tag not closed

### ISSUE THREAD

**Issue by Sofi-bit98** [Wunderbyte-GmbH/moodle-mod_newsletter#53]
**Plugin version:**
v2.3.5-NewYorkTimes (Build: 2023072700)

**Moodle Version:**
Moodle 4.1

**Location:**
mod_newsletter_moodle41_2023072700/db/install.xml line 20: **the tag FIELD not close.**

`<FIELD NAME="aboprofilefield" TYPE="int" LENGTH="10" NOTNULL="true" DEFAULT="0" SEQUENCE="false"/ COMMENT="User profile field for triggering newsletter subscription">`

**Comment by dasistwas** [comment]
That was already fixed but not released on moodle.org. I did now release the new version.
